version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network
  db:
    image: postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge