version: '3.8'
name: improved-ecomm

services:
  backend:
    build:
      context: ../backend
      dockerfile: backend.dockerfile
    command: python app_backend/manage.py runserver 0.0.0.0:8000
    container_name: impr-comm-backend
    volumes:
      - ../backend:/app_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=db://postgres_user:mysecretpassword@db:5432/improved-ecomm_db
    networks:
      - my_network

  frontend:
    image: node:lts-hydrogen
    build:
      context: ../frontend
      dockerfile: frontend.dockerfile
    command: npx serve -s build
    container_name: impr-comm-frontend
    volumes:
      - ../frontend/app_frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network

  db:
    image: postgres:13-alpine
    container_name: impr-comm-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=improved-ecomm_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge