# Generated by Django 4.1.5 on 2023-01-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
